bot-token: "YOUR-BOT-TOKEN-HERE"
command-prefix: "?"
server-id: SERVER-ID-HERE
verified-role: VERIFIED-ROLE-ID-HERE
verification-channel: CHANNEL-ID-HERE
max-verification-emails: 5
admin-channel: CHANNEL-ID-HERE
admin-roles:
  - ROLE-ID-HERE
email-address: "YOUR-EMAIL-ADDRESS-HERE"
aws-region: "ap-southeast-2"
aws-access-key-id: "YOUR-AWS-ACCESS-KEY-ID-HERE"
aws-secret-access-key: "YOUR-AWS-SECRET-ACCESS-KEY-HERE"
